docs/src/quickstart.rst
I have updated the quickstart a little to not litter in the user's home folder and remove information that I think is unimportant.
=> Reiterated the quickstart documentation

Makefile
Signed-off-by: Niclas Hedam <niclas@hed.am>
=> build:make: added 'default' target; user-mode uninstall/install

.github/workflows/selftest.yml, .travis.yml, bin/cij_fetch, bin/cij_reporter, bin/cij_runner, bin/cij_testcases, bin/cij_tlint, bin/cij_trun_to_junit, bin/config_add_opts, bin/rand_str, modules/cij/__init__.py, modules/cij/reporter.py, modules/cij/runner.py, modules/cij/util.py, setup.py, testcases/cijoe_flake8.sh, testplans/cijoe.plan
Adding flake8 to self-test and fixed what it found except for three annotation issues.
=> Makeover flake8

.github/workflows/selftest.yml, modules/cij/runner.py, testcases/cijoe_mypy.sh, testplans/cijoe.plan
Add mypy to selftesting, should help with verifying the cijoe data-model
Need to fix the issues found by mypy before merging it.
=> Makeover mypy

CHANGELOG.md, bin/cij_analyser, bin/cij_extractor, bin/cij_plotter, bin/cij_reporter, bin/cij_trun_to_junit, modules/cij/extractors/fio_json_read.py, modules/cij/reporter.py, modules/cij/runner.py, requirements.txt, selftest.sh, templates/report.html
A collection of fixes and then the addition of an initial metric-plotter implementation.
=> Makeover plotter

modules/cij/extractors/fio_json.py, modules/cij/extractors/fio_json_read.py
Signed-off-by: Michael Bang <mi.bang@samsung.com>
=> mod:py:extractors: add evars to fio_json context

src/cijoe/core/transport.py
Signed-off-by: Karl Bonde Torp <k.torp@samsung.com>
=> transport: add errors='replace' when decoding

src/cijoe/core/processing.py
The decoding was implemented incorrectly, this corrects the error
=> processing: fix bug introduced in PR#50

docs/source/usage/index.rst, src/cijoe/cli/cli.py, src/cijoe/core/scripts/example.py, src/cijoe/core/selftest/test_collector.py
Solves #53
@safl I am unsure whether you had another structure in mind. I have tried to reuse as much existing code as possible, but let me know if you have any ideas on how to improve it :)
=> feat(cli): provide standalone execution of cijoe-script

src/cijoe/cli/cli.py
Instead of having the `cijoe --script` cli-option, emit the example script along with example config and workflow when calling `cijoe --example`.
Solves point 3 under "Nice to have" in #73
=> fix(cli/script): emit example script when calling `cijoe --example`

docs/source/packages/core/index.rst, docs/source/packages/core/scripts/get.rst, docs/source/packages/core/scripts/put.rst, src/cijoe/core/scripts/get.py, src/cijoe/core/scripts/put.py, src/cijoe/core/selftest/test_collector.py
Added core scripts for the put and get interface too provide predefined workflow steps for copying files between local and remote
=> feat(core): add put and get scripts

src/cijoe/core/command.py
=> feat(command): add help function for retreiving config variables

docs/source/conf.py, docs/source/resources/configs/index.rst
=> fix(docs): describe how to use private key for transport

docs/source/index.rst, docs/source/prerequisites/index.rst, docs/source/resources/configs/index.rst
Fix typos and document environment variable overrides for configuration variables.
=> Additional documentation changes

Makefile, docs/source/conf.py, docs/source/configs/index.rst, docs/source/index.rst, docs/source/resources/index.rst, src/cijoe/cli/cli.py, src/cijoe/core/configs/default-config.toml, src/cijoe/core/processing.py, src/cijoe/core/scripts/example.py, src/cijoe/core/selftest/test_workflow.py, src/cijoe/core/workflows/example-workflow.yaml
This fixes issues https://github.com/refenv/cijoe/issues/103 and https://github.com/refenv/cijoe/issues/105 along with a bit of improvement to the documentation.
=> Misc. docs and fixes

.github/workflows/selftest.yml, Makefile, pyproject.toml, src/cijoe/core/selftest/test_workflow.py
In preparation / caught while iterating on:
- https://github.com/refenv/cijoe/pull/109
- https://github.com/refenv/cijoe/pull/112
=> Misc fixes

.github/workflows/cijoe_pkg_qemu.yml, src/cijoe/qemu/configs/example_config_build.toml, src/cijoe/qemu/configs/example_config_default.toml, src/cijoe/qemu/scripts/build.py, src/cijoe/qemu/scripts/qemu_system_version.py, src/cijoe/qemu/workflows/example_workflow_build.yaml, src/cijoe/qemu/workflows/example_workflow_default.yaml
Refactored the codebase to enable testing of usage examples in the cijoe qemu package. These changes are non-breaking and lay the groundwork for further improvements.
=> preparation for qemu package refatoring

.github/cijoe-docker/Dockerfile
Add all depedencies that are necessary for running the linux example
=> fix(docker): add linux example dependencies

Makefile, src/cijoe/qemu/configs/example_config_default.toml, src/cijoe/qemu/workflows/example_workflow_default.yaml
A couple of fixes and improvements.
=> misc. fixes in preparation for qemu refactor

.gitignore
Vscode setttings directory is deleted every time `make all` is executed. This would fix it. The same goes for virtual environment
=> change(gitignore): Add vscode and venv to git ignore

src/cijoe/core/scripts/cmdrunner.py, src/cijoe/core/scripts/get.py, src/cijoe/core/scripts/put.py, src/cijoe/fio/scripts/build.py, src/cijoe/fio/scripts/install.py, src/cijoe/gha/scripts/runner_download.py, src/cijoe/gha/scripts/runner_remove.py, src/cijoe/gha/scripts/runner_setup.py, src/cijoe/linux/scripts/build_kdebs.py, src/cijoe/linux/scripts/transfer_and_install_kdebs.py, src/cijoe/qemu/scripts/guest_initialize.py, src/cijoe/qemu/scripts/install.py, src/cijoe/qemu/scripts/qemu_version.py, src/cijoe/qemu/wrapper.py, src/cijoe/system_imaging/scripts/diskimage_from_cloudimage.py
=> Error handling in cijoe scripts

docs/source/resources/templates/template.py, docs/source/workflows/index.rst, src/cijoe/cli/cli.py, src/cijoe/core/resources.py, src/cijoe/core/scripts/cmdrunner.py, src/cijoe/core/scripts/example_script_default.py, src/cijoe/core/scripts/get.py, src/cijoe/core/scripts/put.py, src/cijoe/core/scripts/reporter.py, src/cijoe/core/scripts/repository_prep.py, src/cijoe/core/scripts/testrunner.py, src/cijoe/fio/scripts/build.py, src/cijoe/fio/scripts/check.py, src/cijoe/fio/scripts/install.py, src/cijoe/gha/scripts/runner_download.py, src/cijoe/gha/scripts/runner_remove.py, src/cijoe/gha/scripts/runner_setup.py, src/cijoe/linux/scripts/build_kdebs.py, src/cijoe/linux/scripts/null_blk.py, src/cijoe/linux/scripts/sysinfo.py, src/cijoe/linux/scripts/transfer_and_install_kdebs.py, src/cijoe/qemu/scripts/build.py, src/cijoe/qemu/scripts/guest_initialize.py, src/cijoe/qemu/scripts/guest_kill.py, src/cijoe/qemu/scripts/guest_start.py, src/cijoe/qemu/scripts/install.py, src/cijoe/qemu/scripts/qemu_version.py, src/cijoe/system_imaging/scripts/diskimage_from_cloudimage.py, src/cijoe/system_imaging/scripts/dockerimage_from_diskimage.py, tests/core/test_workflow.py
⚠️ This is dependent on #163 (so first 2 commits are not part of this PR)
=> Removal of step parameter from cijoe script entry function

tests/core/test_cli_example.py
I know this is very minimal, but I think it's the last thing that makes sense to add before closing #128
=> feat(tests/cli): add tests for `search_for_file()`

docs/emit.py, docs/source/packages/core/index.rst, docs/source/packages/core/scripts/cmdrunner.rst, docs/source/packages/core/scripts/example_script_default.rst, docs/source/packages/core/scripts/example_script_testrunner.rst, docs/source/packages/core/scripts/get.rst, docs/source/packages/core/scripts/put.rst, docs/source/packages/core/scripts/reporter.rst, docs/source/packages/core/scripts/repository_prep.rst, docs/source/packages/core/scripts/testrunner.rst, docs/source/packages/linux/index.rst, docs/source/packages/linux/scripts/build_kdebs.rst, docs/source/packages/linux/scripts/null_blk.rst, docs/source/packages/linux/scripts/sysinfo.rst, docs/source/packages/qemu/index.rst, docs/source/packages/qemu/scripts/build.rst, docs/source/packages/qemu/scripts/guest_initialize.rst, docs/source/packages/qemu/scripts/guest_kill.rst, docs/source/packages/qemu/scripts/guest_start.rst, docs/source/packages/qemu/scripts/install.rst, docs/source/packages/qemu/scripts/qemu_version.rst, docs/source/packages/system_imaging/index.rst, docs/source/packages/system_imaging/scripts/diskimage_from_cloudimage.rst, docs/source/packages/system_imaging/scripts/dockerimage_from_diskimage.rst, docs/source/testrunner/index.rst, docs/source/usage/index.rst, docs/source/workflows/index.rst, src/cijoe/core/scripts/testrunner.py
This PR addresses the remaining checkboxes in #68
=> Docs: links to package scripts

src/cijoe/core/scripts/wait_for_ssh.py, src/cijoe/qemu/workflows/example_workflow_guest_aarch64.yaml, src/cijoe/qemu/workflows/example_workflow_guest_x86_64.yaml, tests/core/test_collector.py
This script can be useful for other transports than just QEMU guests.
=> refactor(scripts): move "wait fo ssh" script to core package
