refenv/cijoe

- Dockerfile
- bin/cijoe
- docs/src/docker.rst
- docs/src/index.rst
The Dockerfile will create a docker container that is equivalent to running the _cijoe_ command. I have created a docker repo on [DockerHub](https://hub.docker.com/repository/docker/cijoe/cijoe). We should setup travis to push to there when releases are created.
> Initial Docker container

- bin/cij_testcases
- modules/cij/reporter.py
- modules/cij/runner.py
- templates/report.html
Use dataclasses instead of dicts. This should help make the code safer
and more maintainable by making it easier for the Python runtime and IDEs to
e.g. automatically identify typos in field names.
> cij: use dataclasses instead of dicts

- .github/workflows/selftest.yml
Checking to see the effect on shellcheck
> ci: change from ubuntu latest to explicitly testing 20.04 and 18.04

- modules/cij.sh
- modules/ssh.sh
A fix to the ``ssh:cmd`` and addition an addition of ``cij::cmd``.
The point of ``cij::cmd`` is to provide a helper in testcases for the actual command-invocation, such that one does write ``ssh::cmd`` directly in the testcase but rather via ``cij::cmd`` instead, ``cij::cmd`` then invokes the command via a transport such as SSH or via local command execution. It is in preparation for fixing up that lack on indirection but added now such that new examples can use it.
> Makeover fixes

- testcases/extc_05_fio.sh
- testplans/example_05_fio.plan
This is a example of wrapping fio with a cijoe testcase that can be instrumented from the testplan.
It also serves as an example of the type of data produced by a testcase which needs further post-processing in the form of extraction from output logs, transformation into formats for plotting and performance metric evaluation.
> Makeover fio

- CHANGELOG.md
- bin/cij_fetch
- bin/cij_reporter
- bin/cij_runner
- bin/cij_testcases
- bin/cij_tlint
- modules/cij/reporter.py
- modules/cij/runner.py
- modules/cij/util.py
- selftest.sh
- templates/report.html
The basic functionality is in place; the runner can execute multiple testplans and visualize multiple plans in a single report. However, the following needs attention before merge:
* ~~The report-template, it is currently showing testplan info such as evars, hook-output etc. as part of the testrun, this should be moved down into the testplan-section.~~
* ~~The states of: status, progress, and wallc needs some verification, they are not accounted correctly.~~
* ~~TestPlan now has "progress", however, it is not accounted correctly, this needs fixing.~~
Providing it now for early review and to determine possible collisions with the analyse feature.
> Support for multiple testplans per testrun

- bin/cij_plotter
This provides a way for the user to format dataset-labels using dataset context.
```bash
cij_plotter \
--output results/latest \
--metric iops \
--show 1 \
--label-fmt="{{ioengine}}/{{bs}}"
```
> Makeover plotlabels

- src/cijoe/core/processing.py
Currently cijoe will run into errors like:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xef in position 60: invalid continuation byte
This change fixes these errors
> processing: decode with errors='replace' when reading

- src/cijoe/cli/cli.py
- src/cijoe/core/resources.py
It would be useful to give a tag for a workflow run
while running cijoe during development. This option enables
to give a tag that will be stored in the workflow.state. The same
text will be used as a prefix with timestamp while storing the results
in the archive folder.
Example usage:
```bash
$ cijoe -c default.config -w example.workflow -t "directIO" --tag "io_uring"
$ ls -la cijoe-archive/
directIO-io_uring-2023-02-07_06:44:34
```
> Add description option for a workflow run and a clean up to --archive option

- src/cijoe/core/transport.py
The commands for setting environment variables in csh (default on FreeBSD) and in cmd and PowerShell (Windows) are different than in sh.
Which shell is used, should be set in the config file. If none is set, sh is assumed.
> fix(transport): add support for env variables in csh, cmd and pwsh

- docs/source/resources/configs/index.rst
- src/cijoe/core/command.py
- src/cijoe/core/configs/transport-ssh.toml
- src/cijoe/core/scripts/testrunner.py
- src/cijoe/core/transport.py
- src/cijoe/fio/selftest/test_fio_wrapper.py
- src/cijoe/linux/scripts/transfer_and_install_kdebs.py
- src/cijoe/linux/selftest/test_null_blk.py
- src/cijoe/qemu/configs/debian-bookworm-amd64-kvm.toml
- src/cijoe/qemu/configs/debian-bookworm-arm64-hvf.toml
- src/cijoe/qemu/configs/debian-bullseye-amd64-kvm.toml
- src/cijoe/qemu/configs/default-config.toml
- src/cijoe/qemu/configs/freebsd-13-amd64-kvm.toml
Move the top-level item `transport` under top-level item `cijoe` to match with all other top level identifiers in the configuration-file.
Closes #60
> refactor(config): move transport item to cijoe

- src/cijoe/core/resources.py
This import is unused in the code - but it makes installing cijoe on MacOS more painful than it should be.
> fix(resources): remove unused setuptools import

- src/cijoe/core/resources.py
Since cijoe-scripts are dynamically loaded, the current work directory is not available as import path. Therefore, we inject the parent path to sys.path in order to allow imports of scripts from the same directory.
> fix(core): add script parent path to sys.path

- setup.cfg
- src/cijoe/cli/cli.py
- src/cijoe/core/resources.py
- src/cijoe/core/selftest/test_collector.py
- src/cijoe/core/templates/example-tmp-workflow.yaml.jinja2
Allows cijoe-scripts to be run with cijoe, so for example `cijoe cijoe-script.py`. The `.py` suffix is reserved for python scripts, and cannot be used in workflow step names. 
Multiple cijoe-scripts can be executed in sequence as a workflow, for example `cijoe script1.py script2.py`, but requires that all arguments ends with `.py`. If one or more arguments does not end with `.py`, the arguments are treated as workflow steps.
> Stand-alone execution

- src/cijoe/cli/cli.py
- src/cijoe/core/resources.py
- src/cijoe/core/selftest/conftest.py
When running cijoe-scripts with the `cijoe` cli, they might be out of reach for the cijoe auto-discovery. In order to allow execution of the scripts, add parent paths to collected paths.
Solves point 4 under "Nice to have" in https://github.com/refenv/cijoe/issues/73
> fix(cli): add standalone script paths to search paths for auto-discovery 

- src/cijoe/core/transport.py
`get_pty=True` must have some other side-effects than anticipated, as if `cmd` is set to for example `powershell "echo hi"`, then `stdout.channel.exit_status_ready()` will never return True. The parameter is not necessary for streaming output in real-time though, so we combine `stdout` and `stderr` with the `set_combine_stderr(True)` instead.
> bugfix(transport): combine stdout and stderr instead of using get_pty

- docs/source/usage/index.rst
- src/cijoe/cli/cli.py
- src/cijoe/core/scripts/example.py
Now that standalone cijoe scripts can be run with
`cijoe path/to/cijoe-script.py`, we drop support for running standalone cijoe scripts with the python intepreter. This way we only have one entrypoint of running cijoe-scripts, which ultimately makes both the cijoe scripts and cijoe as a tool simpler.
Solves the comment from Oct 16 2024 on issue #73
> fix(cli): drop support for running scripts with python interpreter

- docs/source/resources/configs/index.rst
- src/cijoe/core/command.py
- src/cijoe/core/transport.py
- src/cijoe/linux/scripts/transfer_and_install_kdebs.py
- src/cijoe/qemu/configs/debian-bookworm-amd64-kvm.toml
- src/cijoe/qemu/configs/debian-bookworm-arm64-hvf.toml
- src/cijoe/qemu/configs/debian-bullseye-amd64-kvm.toml
- src/cijoe/qemu/configs/default-config.toml
- src/cijoe/qemu/configs/freebsd-13-amd64-kvm.toml
Added the `endpoint_name` parameter to `cijoe.run(...)`, which allows users to specify which endpoint they want to execute commands on. Endpoints are defined in the configuration file under the key `cijoe.transport` with user-defined names. If the `endpoint_name` parameter is not given, the command is executed on the first defined endpoint. If no endpoints are defined, the command is executed on the initiator.
Solves issue #75
> feat(transport): allow defining multiple transport endpoints

- .github/workflows/selftest.yml
- src/cijoe/core/misc.py
- src/cijoe/qemu/configs/debian-bookworm-amd64-kvm.toml
- src/cijoe/qemu/configs/debian-bookworm-arm64-hvf.toml
- src/cijoe/qemu/configs/debian-bullseye-amd64-kvm.toml
- src/cijoe/qemu/configs/default-config.toml
- src/cijoe/qemu/configs/freebsd-13-amd64-kvm.toml
- src/cijoe/qemu/scripts/guest_init_using_bootimage.py
- src/cijoe/qemu/scripts/guest_init_using_cloudinit.py
- src/cijoe/qemu/wrapper.py
Before, images were not downloaded if a file on the given path already existed. Now, checksums are compared to determine whether the image should be downloaded. Configuration files must be expanded with a qemu.guest.<init>.url_csum which points to the checksum file of the downloaded image.
Solves issue #83
----
@safl, I create this as a draft for now. I still need to update the example configuration files with the `url_csum`, but as I don't have access to Digital Ocean, I think I need your help on this one. 
Also, I don't know if I'm 100% satisfied with the name of the `_get_img()` method - maybe you have an idea? The method contains all logic for checking checksums and downloading the new image if necessary, and then returns the path to the newly-downloaded or already-existing image.
> feat(qemu): add checksum checks on qemu images

- .github/cijoe-docker/Dockerfile
- .github/workflows/cijoe_docker.yml
To test the cijoe QEMU package and the system-imaging packages, they should be verified using GitHub workflows. This preparation involves providing a Docker image with QEMU installed, which can be used in a GitHub workflow.
There is also a fix in here as I stumbled upon it.
> Add a 'cijoe-docker' image containing everything needed for cijoe and packages

- .github/cijoe/README.rst
- .github/workflows/system_imaging.yml
- src/cijoe/system_imaging/auxiliary/Dockerfile
- src/cijoe/system_imaging/auxiliary/cloudinit-alpine-metadata.meta
- src/cijoe/system_imaging/auxiliary/cloudinit-alpine-userdata-x86_64.user
- src/cijoe/system_imaging/auxiliary/dockerignore
- src/cijoe/system_imaging/configs/default-config.toml
- src/cijoe/system_imaging/scripts/diskimage_from_cloudimage.py
- src/cijoe/system_imaging/scripts/dockerimage_from_diskimage.py
- src/cijoe/system_imaging/selftest/test_nop.py
- src/cijoe/system_imaging/workflows/example-workflow.yaml
This prepares for separating QEMU guest control from the creation
of .qcow2 boot images. Decoupling these components makes the
qemu-wrapper module less dependent on boot and cloud images, allowing
it to be refactored to operate independently of the cijoe configuration
file. This change enables controlling QEMU via custom logic in start/
stop scripts instead of relying on configuration file conventions.
Additionally, it encapsulates various system images, including their
origin locations, deployment locations, and the scripts required to
build them.
Also, the default example of using the package, as emitted by:
cijoe --example system_imaging
Is exercised via ci, this practice is what we aim for going forward, to
ensure proper testing of cijoe itself.
> Add a "system imaging" package

- .github/cijoe-docker/Dockerfile
meson is needed to build qemu from source, which is one of the built-in scripts and examples of the 'qemu' package.
> feat(ci): add 'meson' to 'cijoe-docker'

- .github/cijoe-docker/Dockerfile
glib2 is needed to build qemu from source, which is one of the built-in scripts and examples of the 'qemu' package.
> feat(ci): add 'glib2' to 'cijoe-docker'

- .github/workflows/cijoe_packages.yml
- src/cijoe/fio/configs/example_config_benchmark.toml
- src/cijoe/fio/configs/example_config_default.toml
- src/cijoe/fio/workflows/example_workflow_default.yaml
The example configuration file is split into build and benchmark sections to simplify examples, ensuring each file contains only entries relevant to the specific use case.
Additional work is required on the package. This change exercises the build, install, and check scripts, but the more complex fio-wrapper script is not yet covered and the documentation needs updating as well.
> feat(gha): add verification of the cijoe package, fio

- .github/cijoe-docker/Dockerfile
This pull request adds the two python packages "coverage" and "pytest coverage" to the dockerfile.
These packages are added to the docker container so that it is not needed to be explicitly installed in the github action workflows.
> Add coverage dependencies to docker container

- .github/cijoe-docker/Dockerfile
The `--include-deps` flag was mistakenly added to the pip install(pipx) command for the pytest-cov package
> fix(docker): remove errornoeous `--include-deps` flag from pipx install

- .github/workflows/cijoe_packages.yml
- src/cijoe/cli/cli.py
The previous method of discovering examples was cumbersome. Users had to run `cijoe --resources` and manually search for files with "example" in their names, then piece together configuration files, workflows, and scripts.
This refactor changes the behavior of the `cijoe --example` command to make example discovery more intuitive:
- Running `cijoe --example` now lists all available examples.
- Running `cijoe --example qemu` outputs all examples specific to the `qemu` package.
- Running `cijoe --example qemu.build` outputs only the `qemu.build` example.
Additionally, examples are now output into a subfolder of the current working directory in the format:
cijoe-example-<pkg_name>.<example>
This improves usability and streamlines access to examples.
This fixes …
> refactor(cli): improve example discovery and organization

- .github/workflows/cijoe_packages.yml
- src/cijoe/core/selftest/test_cli_example.py
- src/cijoe/qemu/configs/example_config_bootimage.toml
- src/cijoe/qemu/configs/example_config_cloudinit.toml
- src/cijoe/qemu/scripts/qemu_system_version.py
- src/cijoe/qemu/workflows/example_workflow_bootimage.yaml
- src/cijoe/qemu/workflows/example_workflow_cloudinit.yaml
The cloud-init and bootimage initialization examples were not being tested. This PR addresses that by enabling them through two explicit examples.
> Expand testing of cijoe package; qemu

- .coveragerc
- .github/workflows/verify_and_publish.yml
- .gitignore
- Makefile
- src/cijoe/core/resources.py
This is a rebase of https://github.com/refenv/cijoe/pull/111 on top of main.
> Collection and publication of coverage-data

- docs/source/200_quickstart.cmd
- docs/source/300_lint.cmd
- docs/source/420_usage_workflow_all.cmd
- docs/source/450_usage_workflow_subset.cmd
- docs/source/scripts/index.rst
- docs/source/usage/index.rst
- src/cijoe/cli/cli.py
- src/cijoe/core/resources.py
- src/cijoe/core/scripts/example_script_default.py
- tests/core/test_workflow.py
This commit changes the way cijoe scripts and workflows are run. The interface is now `cijoe {workflow path|script name|script path} [...options]`.
If the positional arg is referencing a stand-alone script, additional cli args can be defined by adding a function to the cijoe script file of the form `add_args(parser: ArgumentParser)`. This will allow us to remove the `step` argument in the cijoe script main function at a later point.
If positional arg is referencing a workflow file, additional positional arguments will be treated as step arguments, defining which steps in the workflow will be run.
>  feat(cli): add subparsers for workflows and scripts 

- docs/source/conf.py
- docs/source/scripts/index.rst
- docs/source/testrunner/index.rst
- src/cijoe/cli/cli.py
- src/cijoe/core/scripts/reporter.py
- src/cijoe/core/scripts/testrunner.py
- src/cijoe/linux/scripts/build_kdebs.py
A fix for the boolean script arguments that as of now are incorrectly evaluated with the `bool()` function, as both "true" and "false" are evaluated to `True`.
Also commit "fix(core/cli) ......" fixes an error in the way script arguments were added in the workflow, because this approach broke when running the scripts individually with the cli tool
> Boolean script arguments

- docs/source/configs/index.rst
- src/cijoe/cli/cli.py
cijoe can be run with multiple configuration files by specifying the `-c` flag multiple times in the CLI. Later files (in the order of when they apper in the command) override conflicting keys.
Will solve #106
> feat(core/config): allow multiple config files

- src/cijoe/qemu/scripts/guest_wait_for_termination.py
- src/cijoe/qemu/workflows/example_workflow_guest_aarch64.yaml
- src/cijoe/qemu/workflows/example_workflow_guest_x86_64.yaml
- src/cijoe/qemu/wrapper.py
Move the SIGTERM signal logic from the `Guest.kill()` to its own method `Guest.wait_for_termination(timeout)`, which allows us to create a script that gives access to this functionality without force-killing the process
This should be what is needed to fix #82
> fix(qemu/wrapper): add termination logic to qemu wrapper and script 

- src/cijoe/cli/cli.py
Without the custom config append action, the config cli argument was overwritten to the default value (empty) by the subparser, if the config argument was positioned before the workflow/script argument.
> fix(cli/configs): add custom append action for config arg

- src/cijoe/core/templates/report-workflow.html.jinja2
The tests in a testreport can now be filtered based on the status of the test (passed/failed/skipped) by clicking the buttons in the test report summary.
> feat(core/report): add functionality for filtering in testreport

- .github/workflows/verify_and_publish.yml
- src/cijoe/core/misc.py
- src/cijoe/system_imaging/configs/example_config_aarch64.toml
- src/cijoe/system_imaging/configs/example_config_x86_64.toml
- src/cijoe/system_imaging/scripts/diskimage_from_cloudimage.py
- src/cijoe/system_imaging/scripts/dockerimage_from_diskimage.py
If cloud images are compressed when downloaded, the user can provide a `decompressed_path` key to the `system-imaging.images.*.cloud` config to indicate that the diskimage_from_cloudimage script should decompress the image after downloading.
If `decompressed_path` is not defined, we assume the image is not compressed.
Should solve #186
> feat(system-imaging): add decompression of cloud images

- src/cijoe/cli/cli.py
- src/cijoe/core/templates/report-workflow.html.jinja2
- src/cijoe/qemu/scripts/guest_wait_for_ssh.py
- src/cijoe/qemu/workflows/example_workflow_guest_aarch64.yaml
- src/cijoe/qemu/workflows/example_workflow_guest_x86_64.yaml
- src/cijoe/qemu/wrapper.py
- src/cijoe/system_imaging/auxiliary/cloudinit-linux-common-userdata.user
Fixes for:
- Multiple configs overwriting eachother: merge dicts recursively
- UNIX assumption in Guest.wrapper: allow definition of boot-driver
Added:
- Script for waiting for guest SSH to be ready, should solve #194 
- "copy" button in report which lets you copy the commands to the clipboard, so you don't have to mark it yourself.
> Fixes for smaller issues
